CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(100) NOT NULL,
	stars INTEGER,
	status BOOLEAN,
	country VARCHAR(255),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)